# Interface virtual de túnel (camada 3 – IP)
dev tun

# Define este nó como cliente OpenVPN
client

# Protocolo de transporte
proto udp

# Endereço e porta do servidor OpenVPN
remote 200.50.100.10 1194

# Solicita configurações do servidor (rotas, DNS, etc.)
pull

# Certificado da Autoridade Certificadora
ca /etc/openvpn/client/ca.crt

# Certificado público do cliente
cert /etc/openvpn/client/vpn-client-01.crt

# Chave privada do cliente
key /etc/openvpn/client/vpn-client-01.key

# Chave de autenticação TLS
tls-auth /etc/openvpn/client/ta.key 1

# Versão mínima do TLS
tls-version-min 1.2

# Criptografia do túnel de dados
cipher AES-256-GCM

# Algoritmo de autenticação
auth SHA256

# Mantém túnel e chaves após reconexão
persist-tun
persist-key

# Executa o processo com usuário sem privilégios
user nobody
group nogroup

# Nível de verbosidade do log
verb 3
