runtime! debian.vim

syntax on
set background=dark

"set showcmd		" Show (partial) command in status line.
"set showmatch		" Show matching brackets.
"set smartcase		" Do smart case matching
"set incsearch		" Incremental search
"set autowrite		" Automatically save before commands like :next and :make
"set hidden		" Hide buffers when they are abandoned
"set mouse=a		" Enable mouse usage (all modes)
set ignorecase		" Do case insensitive matching
set number

if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif

